### ISSUE TITLE
Native Lib not found

### ISSUE THREAD

**Issue by SudoDios** [WindySha/bypassHiddenApiRestriction#2]
java.lang.UnsatisfiedLinkError: dlopen failed: library "libbypassRestriction.so" not found

**Comment by Aspirers** [comment]
> java.lang.UnsatisfiedLinkError: dlopen failed: library "libbypassRestriction.so" not found

Same happens with me 

> java.lang.UnsatisfiedLinkError: dlopen failed: library "libc++_shared.so" not found:

**Comment by WindySha** [comment]
how is it used, is there a sample?

**Comment by WindySha** [comment]
May be you should set this in build.gradle
```
externalNativeBuild {
            cmake {
                cppFlags ""
                arguments '-DANDROID_STL=c++_shared'
            }
        }
```
